<?php

namespace AppBundle\Repository;

/**
 * HeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeroRepository extends \Doctrine\ORM\EntityRepository
{
}
